// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RelicDealFinder.Data;

#nullable disable

namespace RelicDealFinder.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261006180713_RefreshRuns")]
    partial class RefreshRuns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("RelicDealFinder.Models.Market.MarketRelic", b =>
                {
                    b.Property<string>("Slug")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("CommonRewardSlugs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("IntPotentialPlat")
                        .HasColumnType("REAL");

                    b.Property<double?>("RadPotentialPlat")
                        .HasColumnType("REAL");

                    b.Property<string>("RareRewardSlug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("UncommonRewardSlugs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Slug");

                    b.ToTable("Relics");
                });

            modelBuilder.Entity("RelicDealFinder.Models.Market.PrimePart", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameRef")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Vaulted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PrimeParts");
                });

            modelBuilder.Entity("RelicDealFinder.Models.Refresh.RefreshRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Errors")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PriceLookups")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RelicCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Retries")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RefreshRuns");
                });
#pragma warning restore 612, 618
        }
    }
}
